// <auto-generated />
using System;
using HCAMiniEHR.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HCAMiniEHR.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Healthcare")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HCAMiniEHR.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointment", "Healthcare");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentDate = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorName = "Dr. Anderson",
                            PatientId = 1,
                            Reason = "Annual checkup",
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 2,
                            AppointmentDate = new DateTime(2026, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorName = "Dr. Martinez",
                            PatientId = 2,
                            Reason = "Follow-up consultation",
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 3,
                            AppointmentDate = new DateTime(2026, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorName = "Dr. Thompson",
                            PatientId = 3,
                            Reason = "Blood pressure monitoring",
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 4,
                            AppointmentDate = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorName = "Dr. Lee",
                            PatientId = 4,
                            Reason = "Diabetes management",
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 5,
                            AppointmentDate = new DateTime(2026, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorName = "Dr. Anderson",
                            PatientId = 5,
                            Reason = "Vaccination",
                            Status = "Scheduled"
                        });
                });

            modelBuilder.Entity("HCAMiniEHR.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RecordId")
                        .HasColumnType("int");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("AuditLog", "Healthcare");
                });

            modelBuilder.Entity("HCAMiniEHR.Models.LabOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Results")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.ToTable("LabOrder", "Healthcare");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentId = 1,
                            OrderDate = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            TestName = "Complete Blood Count (CBC)"
                        },
                        new
                        {
                            Id = 2,
                            AppointmentId = 2,
                            OrderDate = new DateTime(2026, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Results = "Normal cholesterol levels",
                            Status = "Completed",
                            TestName = "Lipid Panel"
                        },
                        new
                        {
                            Id = 3,
                            AppointmentId = 3,
                            OrderDate = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            TestName = "Blood Pressure Test"
                        },
                        new
                        {
                            Id = 4,
                            AppointmentId = 4,
                            OrderDate = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Results = "6.2% - Good control",
                            Status = "Completed",
                            TestName = "HbA1c Test"
                        },
                        new
                        {
                            Id = 5,
                            AppointmentId = 5,
                            OrderDate = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            TestName = "Antibody Titer"
                        });
                });

            modelBuilder.Entity("HCAMiniEHR.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Patient", "Healthcare");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1980, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.doe@email.com",
                            FirstName = "John",
                            LastName = "Doe",
                            PhoneNumber = "555-0101"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1992, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jane.smith@email.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            PhoneNumber = "555-0102"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1975, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "michael.j@email.com",
                            FirstName = "Michael",
                            LastName = "Johnson",
                            PhoneNumber = "555-0103"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(1988, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emily.w@email.com",
                            FirstName = "Emily",
                            LastName = "Williams",
                            PhoneNumber = "555-0104"
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(1995, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "david.b@email.com",
                            FirstName = "David",
                            LastName = "Brown",
                            PhoneNumber = "555-0105"
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateTime(1983, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sarah.d@email.com",
                            FirstName = "Sarah",
                            LastName = "Davis",
                            PhoneNumber = "555-0106"
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = new DateTime(1970, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "robert.m@email.com",
                            FirstName = "Robert",
                            LastName = "Miller",
                            PhoneNumber = "555-0107"
                        },
                        new
                        {
                            Id = 8,
                            DateOfBirth = new DateTime(1990, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lisa.w@email.com",
                            FirstName = "Lisa",
                            LastName = "Wilson",
                            PhoneNumber = "555-0108"
                        },
                        new
                        {
                            Id = 9,
                            DateOfBirth = new DateTime(1985, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "james.m@email.com",
                            FirstName = "James",
                            LastName = "Moore",
                            PhoneNumber = "555-0109"
                        },
                        new
                        {
                            Id = 10,
                            DateOfBirth = new DateTime(1978, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "maria.g@email.com",
                            FirstName = "Maria",
                            LastName = "Garcia",
                            PhoneNumber = "555-0110"
                        });
                });

            modelBuilder.Entity("HCAMiniEHR.Models.Appointment", b =>
                {
                    b.HasOne("HCAMiniEHR.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("HCAMiniEHR.Models.LabOrder", b =>
                {
                    b.HasOne("HCAMiniEHR.Models.Appointment", "Appointment")
                        .WithMany("LabOrders")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("HCAMiniEHR.Models.Appointment", b =>
                {
                    b.Navigation("LabOrders");
                });

            modelBuilder.Entity("HCAMiniEHR.Models.Patient", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
